localhost:
  host: localhost
  port: 5432
  user: postgres
  pwd: 123
  branch: ztb-test
  tenantId:
    multiList: 1a
    form: 1a

dev:
  host: 172.31.61.12
  port: 5432
  user: postgres
  pwd: 123
  branch: dev
  tenantId:
    multiList: MQD34N501EX0001
    form: MQD34N501EX0001
    reset: MQD34N501EX0001

test:
  host: 172.31.61.14
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-budget-iteration-3rd
  tenantId:
    multiList: A24SJR50KMK001E
    form: A24SJR50KMK001E
    reset: A24SJR50KMK001E

hotfix:
  host: 172.31.61.16
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: hotfix
  tenantId:
    multiList: T73UGP507KR0001
    form: T73UGP507KR0001
    reset: T73UGP507KR0001

hotfix-inte:
  host: 172.31.61.54
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: hotfix-inte
  tenantId:
    multiList: SLTLFR512JD002H
    form: SLTLFR512JD002H
    reset: SLTLFR512JD002H

hotfix-db:
  host: 172.31.61.20
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: hotfix-emergency
  tenantId:
    multiList: E6R7JR50MCB0015
    form: E6R7JR50MCB0015
    reset: E6R7JR50MCB0015

release:
  host: 172.31.61.18
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: release
  tenantId:
    multiList: PSE5KP504EN000F
    form: PSE5KP504EN000F
    reset: PSE5KP504EN000F


reports:
  host: 172.31.61.24
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-contract
  condition:
  tenantId:
    multiList: LNCEPQ50QX80001
    form: LNCEPQ50QX80001
    reset: LNCEPQ50QX80001

release-db:
  host: 172.31.61.22
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: release
  tenantId:
    multiList: L71RJR50PR80015
    form: L71RJR50PR80015
    reset: L71RJR50PR80015


temp1:
  host: 172.31.61.26
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-public-rp-gl
  tenantId:
    multiList: 0HCEKR50RQ8000V
    form: 0HCEKR50RQ8000V
    reset: 0HCEKR50RQ8000V

temp2:
  host: 172.31.61.28
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-accounting-fact-iteration-8
  tenantId:
    multiList: 87R1UQ50SDB0001
    form: 87R1UQ50SDB0001
    reset: 87R1UQ50SDB0001

temp3:
  host: 172.31.61.30
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-projectSchedule-iteration3
  tenantId:
    multiList: 71F69R50U88001G
    form: 71F69R50U88001G
    reset: 71F69R50U88001G

temp4:
  host: 172.31.61.32
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-contractGenProject
  tenantId:
    multiList: Q8X4HR50VQR0001
    form: Q8X4HR50VQR0001
    reset: Q8X4HR50VQR0001

temp5:
  host: 172.31.61.34
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch:
  tenantId:
    multiList: NVHEKR50WKA002F
    form: NVHEKR50WKA002F
    reset: NVHEKR50WKA002F

temp6:
  host: 172.31.61.36
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch:
  tenantId:
    multiList: ACFEKR50X7V000K
    form: ACFEKR50X7V000K
    reset: ACFEKR50X7V000K

temp7:
  host: 172.31.61.38
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch:
  tenantId:
    multiList: EEMEKR510KR0004
    form: EEMEKR510KR0004
    reset: EEMEKR510KR0004

temp8:
  host: 172.31.61.52
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-project-change
  tenantId:
    multiList: Q2GEKR511M2000L
    form: Q2GEKR511M2000L
    reset: Q2GEKR511M2000L

temp9:
  host: 172.31.61.56
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-multi-org2
  tenantId:
    multiList: S1B4TR5137G001D
    form: S1B4TR5137G001D
    reset: S1B4TR5137G001D

temp10:
  host: 172.31.61.58
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-customizedDetailForm
  tenantId:
    multiList: RKGQTR514JJ001L
    form: RKGQTR514JJ001L
    reset: RKGQTR514JJ001L

temp11:
  host: 172.31.51.15
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-epay2
  tenantId:
    multiList: QXSXHS50KQL0013
    form: QXSXHS50KQL0013
    reset: QXSXHS50KQL0013

temp12:
  host: 172.31.56.145
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-receivedInvoiceManagement
  tenantId:
    multiList: QXSXHS50KQL0013
    form: QXSXHS50KQL0013
    reset: QXSXHS50KQL0013

temp13:
  host: 172.31.51.223
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-receivedInvoiceManagement
  tenantId:
    multiList: QXSXHS50KQL0015
    form: QXSXHS50KQL0015
    reset: QXSXHS50KQL0015

temp14:
  host: 172.31.60.220
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-projectSchedule-phase2
  tenantId:
    multiList: QXSXHS50KQL0017
    form: QXSXHS50KQL0017
    reset: QXSXHS50KQL0017

temp15:
  host: 172.31.60.6
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-virtual-subject
  tenantId:
    multiList: QXSXHS50KQL0019
    form: QXSXHS50KQL0019
    reset: QXSXHS50KQL0019