localhost:
  host: localhost
  port: 5432
  user: postgres
  pwd: 123
  branch: ztb-test
  tenantId:
    multiList: 1a
    uiconfig: 1a

dev:
  host: postgres.nx-dev-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: dev
  tenantId:
    multiList: MQD34N501EX0001
    uiconfig: MQD34N501EX0001
    reset: MQD34N501EX0001

test:
  host: postgres.nx-test-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-budget-iteration-3rd
  tenantId:
    multiList: A24SJR50KMK001E
    uiconfig: A24SJR50KMK001E
    reset: A24SJR50KMK001E

hotfix:
  host: postgres.nx-hotfix-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: hotfix
  tenantId:
    multiList: T73UGP507KR0001
    uiconfig: T73UGP507KR0001
    reset: T73UGP507KR0001

hotfix-inte:
  host: postgres.nx-hotfix-inte-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: hotfix-inte
  tenantId:
    multiList: SLTLFR512JD002H
    uiconfig: SLTLFR512JD002H
    reset: SLTLFR512JD002H

hotfix-db:
  host: postgres.nx-hotfix-db-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: hotfix-emergency
  tenantId:
    multiList: E6R7JR50MCB0015
    uiconfig: E6R7JR50MCB0015
    reset: E6R7JR50MCB0015

release:
  host: postgres.nx-release-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: release
  tenantId:
    multiList: PSE5KP504EN000F
    uiconfig: PSE5KP504EN000F
    reset: PSE5KP504EN000F


reports:
  host: postgres.nx-reports-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-contract
  condition:
  tenantId:
    multiList: LNCEPQ50QX80001
    uiconfig: LNCEPQ50QX80001
    reset: LNCEPQ50QX80001

release-db:
  host: postgres.nx-release-db-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: release
  tenantId:
    multiList: L71RJR50PR80015
    uiconfig: L71RJR50PR80015
    reset: L71RJR50PR80015


temp1:
  host: postgres.nx-temp1-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-public-rp-gl
  tenantId:
    multiList: 0HCEKR50RQ8000V
    uiconfig: 0HCEKR50RQ8000V
    reset: 0HCEKR50RQ8000V

temp2:
  host: postgres.nx-temp2-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-multi-org2
  tenantId:
    multiList: 87R1UQ50SDB0001
    uiconfig: 87R1UQ50SDB0001
    reset: 87R1UQ50SDB0001

temp3:
  host: postgres.nx-temp3-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-projectSchedule-iteration3
  tenantId:
    multiList: 71F69R50U88001G
    uiconfig: 71F69R50U88001G
    reset: 71F69R50U88001G

temp4:
  host: postgres.nx-temp4-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-xiaoguo
  tenantId:
    multiList: Q8X4HR50VQR0001
    uiconfig: Q8X4HR50VQR0001
    reset: Q8X4HR50VQR0001

temp5:
  host: postgres.nx-temp5-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch:
  tenantId:
    multiList: NVHEKR50WKA002F
    uiconfig: NVHEKR50WKA002F
    reset: NVHEKR50WKA002F

temp6:
  host: postgres.nx-temp6-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch:
  tenantId:
    multiList: ACFEKR50X7V000K
    uiconfig: ACFEKR50X7V000K
    reset: ACFEKR50X7V000K

temp7:
  host: postgres.nx-temp7-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch:
  tenantId:
    multiList: EEMEKR510KR0004
    uiconfig: EEMEKR510KR0004
    reset: EEMEKR510KR0004

temp8:
  host: postgres.nx-temp8-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-project
  tenantId:
    multiList: Q2GEKR511M2000L
    uiconfig: Q2GEKR511M2000L
    reset: Q2GEKR511M2000L

temp9:
  host: postgres.nx-temp9-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-multi-org2
  tenantId:
    multiList: S1B4TR5137G001D
    uiconfig: S1B4TR5137G001D
    reset: S1B4TR5137G001D

temp10:
  host: postgres.nx-temp10-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-customizedDetailForm
  tenantId:
    multiList: RKGQTR514JJ001L
    uiconfig: RKGQTR514JJ001L
    reset: RKGQTR514JJ001L

temp11:
  host: postgres.nx-temp11-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-epay2
  tenantId:
    multiList: QXSXHS50KQL0013
    uiconfig: QXSXHS50KQL0013
    reset: QXSXHS50KQL0013

temp12:
  host: postgres.nx-temp12-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-receivedInvoiceManagement
  tenantId:
    multiList: QXSXHS50KQL0013
    uiconfig: QXSXHS50KQL0013
    reset: QXSXHS50KQL0013

temp13:
  host: postgres.nx-temp13-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-inventory
  tenantId:
    multiList: QXSXHS50KQL0015
    uiconfig: QXSXHS50KQL0015
    reset: QXSXHS50KQL0015

temp14:
  host: postgres.nx-temp14-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-projectSchedule-phase2
  tenantId:
    multiList: QXSXHS50KQL0017
    uiconfig: QXSXHS50KQL0017
    reset: QXSXHS50KQL0017

temp15:
  host: postgres.nx-temp15-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-virtual-subject
  tenantId:
    multiList: QXSXHS50KQL0019
    uiconfig: QXSXHS50KQL0019
    reset: QXSXHS50KQL0019

temp16:
  host: postgres.nx-temp16-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-multi-org2
  tenantId:
    multiList: X0S2JU50K7W0001
    uiconfig: X0S2JU50K7W0001
    reset: X0S2JU50K7W0001

temp17:
  host: postgres.nx-temp17-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-budget-print
  tenantId:
    multiList: X0S2JU50K7W0002
    uiconfig: X0S2JU50K7W0002
    reset: X0S2JU50K7W0002

temp18:
  host: postgres.nx-temp18-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-multi-org2
  tenantId:
    multiList: EP97MU51E8B0024
    uiconfig: X0S2JU50K7W0003
    reset: X0S2JU50K7W0003

temp19:
  host: postgres.nx-temp19-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-multi-org2
  tenantId:
    multiList: X0S2JU50K7W0005
    uiconfig: X0S2JU50K7W0005
    reset: X0S2JU50K7W0005

temp20:
  host: postgres.nx-temp20-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-multi-org2
  tenantId:
    multiList: X0S2JU50K7W0004
    uiconfig: X0S2JU50K7W0004
    reset: X0S2JU50K7W0004

temp21:
  host: postgres.nx-temp21-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-purchase-invoice
  tenantId:
    multiList: X0S2JU50K7W0006
    uiconfig: X0S2JU50K7W0006
    reset: X0S2JU50K7W0006

temp22:
  host: postgres.nx-temp22-k8s.e7link.com
  port: 5432
  user: postgres
  pwd: stet44{czars
  branch: feature-purchase-invoice
  tenantId:
    multiList: X0S2JU50K7W0007
    uiconfig: X0S2JU50K7W0007
    reset: X0S2JU50K7W0007