build: /Users/ztb/compile/apps/build

framework: /Users/ztb/compile/apps/framework
init-data: /Users/ztb/compile/apps/init-data

baseapp: /Users/ztb/compile/apps/enterprise/baseapp
project: /Users/ztb/compile/apps/enterprise/project
finance: /Users/ztb/compile/apps/enterprise/finance
procdesign: /Users/ztb/compile/apps/enterprise/procdesign
basebi: /Users/ztb/compile/apps/enterprise/basebi
graphql: /Users/ztb/compile/apps/enterprise/graphql


identity: /Users/ztb/compile/apps/global/identity
reconcile: /Users/ztb/compile/apps/global/reconcile


billType:
  finance: /Users/ztb/compile/apps/enterprise/finance/api/src/main/resources/init-data/BillType.sql
  project: /Users/ztb/compile/apps/enterprise/project/api/src/main/resources/init-data/BillType.sql

multiList:
  init-data: /Users/ztb/compile/apps/init-data/src/main/resources/init-data

form:
  init-data: /Users/ztb/compile/apps/init-data/src/main/resources/init-data